# Slightly adapted from docker4drupal.
version: "2"

services:
  # The database container.
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    # Pass environment variables to the container.
    environment:
      # See all available mariadb variables at https://github.com/wodby/mariadb.
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    # Persistent data for this container.
    volumes:
      # See README.md in /docker/mariadb-init.
      - ./mariadb-init:/docker-entrypoint-initdb.d  

  # The php container.
  php:
# Only the php 7 images have all the Drupal 8 configuration.
#  wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.1-2.1.0
#    image: wodby/drupal-php:7.0-2.1.0
#    image: wodby/drupal-php:5.6-2.1.0
#    image: wodby/drupal-php:5.3-2.1.0
    # Pass environment variables to the container.
    environment:
      # See all available PHP variables at https://github.com/wodby/php.
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_TIMEZONE: America/New_York
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    # Persistent data for this container.
    volumes:
      - docker-sync:/var/www/html
      - ~/.ssh:/root/.ssh

  # The web container.
  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
# Need 8.1.13 to get fixes for private files.
    image: wodby/drupal-nginx:8-1.13-2.4.0
#   image: wodby/drupal-nginx:8-1.10-2.1.0
#    image: wodby/drupal-nginx:7-1.10-2.1.0
#    image: wodby/drupal-nginx:6-1.10-2.1.0
    depends_on:
      - php
    # Pass environment variables to the container.
    environment:
      # See all available NGINX variables at https://github.com/wodby/php.
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    # Persistent data for this container, map host to container locations.
    volumes:
      - docker-sync:/var/www/html
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}.docker.localhost"

#  varnish:
#    image: wodby/drupal-varnish:4.1-2.1.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.drupal.docker.localhost'

#  redis:
#    image: wodby/redis:3.2-2.1.0

#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mariadb
#      PMA_USER: drupal
#      PMA_PASSWORD: drupal
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - 'traefik.backend=pma'
#      - 'traefik.port=80'
#      - "traefik.frontend.rule=Host:pma.${COMPOSE_PROJECT_NAME}.docker.localhost"

#  solr:
## wodby/drupal-solr:[DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-solr:8-6.4-2.0.0
##    image: wodby/drupal-solr:8-6.3-2.0.0
##    image: wodby/drupal-solr:8-5.5-2.0.0
##    image: wodby/drupal-solr:7-6.4-2.0.0
##    image: wodby/drupal-solr:7-6.3-2.0.0
##    image: wodby/drupal-solr:7-5.5-2.0.0
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - "traefik.frontend.rule=Host:solr.${COMPOSE_PROJECT_NAME}.docker.localhost"

  # This is the mail service container.
  mailhog:
    image: mailhog/mailhog
    labels:
      - "traefik.backend=mailhog"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.${COMPOSE_PROJECT_NAME}.docker.localhost"

  # This is the network management container.
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
     # - '8080:8080' # Dashboard
    # Persistent data for this container.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#  node:
#    image: node:7-alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - "traefik.frontend.rule=Host:front.${COMPOSE_PROJECT_NAME}.docker.localhost"
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: wodby/memcached:1.4-2.0.0

# The volume where data needs to be persisted and shared with the host.
volumes:
  docker-sync:
    external: true
