# Add ssl support, requires access to all urls with HTTPS.
# 1) To create certificate:
#   $ mk dir ~/ssl/certs
#   $ openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ~/ssl/certs/key.pem -out ~/ssl/certs/cert.pem
# 2) Copy these contents to docker-compose.override.yml

version: "2"

services:

  php:
    volumes:
      - ~/.ssh:/root/.ssh

  traefik:
    command: -c /dev/null --web --docker --logLevel=INFO --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
    ports:
      - '4443:443'
    volumes:
      - ~/ssl/certs:/certs/
