# Add ssl support, access all urls with HTTPS.
# See README.md for more information.

version: "2"

services:

  traefik:
    command: -c /dev/null --web --docker --logLevel=INFO --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/cert.pem,/certs/key.pem" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
    ports:
      - '4443:443'
    volumes:
      - ~/ssl/certs:/certs/
