# When using Docker-sync, copy this file to top level, /docker-sync.yml

version: "2"

syncs:
  docker-sync:
    src: './'
    sync_userid: '82'
    sync_excludes: ['.gitignore', '.git/', '.idea/']
    volumes:
      - docker-sync:/var/www/html
#  docker-sync-another-project:
#    src: '/absolute/path/to/project/codebase'
#    sync_userid: '82'
#    sync_excludes: ['.gitignore', '.git/', '.idea/']
